# Force CI cache refresh - correct worker name is quanta-stream-proxy
name = "quanta-stream-proxy"
account_id = "f00ba328036ba6fad81a8b90ce0dd676"
main = "src/index.ts"
compatibility_date = "2025-09-29"
compatibility_flags = ["nodejs_compat"]

[vars]
SUPABASE_URL = "https://mnlippoyqiirugpdsvja.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ubGlwcG95cWlpcnVncGRzdmphIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwMjc0OTcsImV4cCI6MjA3NDYwMzQ5N30.Fo6a0pLdu8m6tK0aceBIg5rXGcaV6FdMKJxF8mGFyN4"
SENTRY_ENV = "production"

[[kv_namespaces]]
binding = "QUANTA_CACHE"
id = "70d6ab88abec407dbd1687ff9eb15cc2"

[triggers]
crons = ["*/5 * * * *"]
