name = "quanta-web"
pages_build_output_dir = "apps/web/.next"
compatibility_date = "2025-09-28"
compatibility_flags = ["nodejs_compat"]

[vars]
NEXT_PUBLIC_SUPABASE_URL = "https://mnlippoyqiirugpdsvja.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ubGlwcG95cWlpcnVncGRzdmphIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwMjc0OTcsImV4cCI6MjA3NDYwMzQ5N30.Fo6a0pLdu8m6tK0aceBIg5rXGcaV6FdMKJxF8mGFyN4"

[[kv_namespaces]]
binding = "QUANTA_CACHE"
id = "placeholder_kv_id"
preview_id = "placeholder_preview_id"
